# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Environmental Topics and Analysis
description: >- 
  This site contains the information that students will need to complete BIO 331 at William Peace University
github_username: maryglover
minimal_mistakes_skin: contrast
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

#include:
#  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Mary Glover"
  bio    : "Welcome to BIO 331!"
  links:
   - label: "Pressly 100B (in between 100 and 102)"
      icon: "fab fa-fw fa-github"
    - label: "Office Hours:"
      icon: "fab fa-solid fa-clock"
    - label: "Or by appointment"
      icon: "fab fa-solid fa-link"
      url: "https://peace.starfishsolutions.com/starfish-ops/dl/instructor/serviceCatalog.html?bookmark=connection/1243084/schedule"
    - label: "Class Chat"
      icon: "fab fa-brands fa-google"
      url: "https://chat.google.com/room/AAQA35tszjY?cls=7"
   - label: "Syllabus"
      icon: "fab fa-solid fa-file"
      url: /bio231-syllabus.pdf
    - label: "R Posit Cloud"
      icon: "fab fa-solid fa-r"
      url: "https://posit.cloud/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/maryglover"

#footer:
#  links:
  #  - label: "Twitter"
  #    icon: "fab fa-fw fa-twitter-square"
  #    url: "https://twitter.com/"
   # - label: "GitHub"
  #    icon: "fab fa-fw fa-github"
   #   url: "https://github.com/"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
     # url: "https://instagram.com/"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: true

#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/

bio231-syllabus:
  path: /syllabus/